[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
somnia_testnet = "https://dream-rpc.somnia.network"

# [etherscan]
# somnia_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://somnia-testnet.blockscout.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
